language: scala

services:
  - docker

cache:
  directories:
    - "$HOME/.ivy2"

before_cache:
  - rm -Rf $HOME/.ivy2/.sbt.cache.lock
  - rm -Rf $HOME/.ivy2/.sbt.ivy.lock

matrix:
  include:
    - stage: Prerequisites (level -2)
      script: sh -e scripts/build-prereq.sh sbt-testlogconfig sbt-jbake sbt-filterresources

    - stage: Prerequisites (level -1)
      script: sh -e scripts/build-prereq.sh blended

    - stage: Build
      script:
        - wget -P docker/blended.docker.base/files/ https://cdn.azul.com/zulu/bin/zulu8.33.0.1-jdk8.0.192-linux_x64.tar.gz
        - docker build -t atooni/blended-base docker/blended.docker.base
        - sbt publishLocal

    - stage: Test
      script:
        - wget -P docker/blended.docker.base/files/ https://cdn.azul.com/zulu/bin/zulu8.33.0.1-jdk8.0.192-linux_x64.tar.gz
        - docker build -t atooni/blended-base docker/blended.docker.base
        - sbt test

script: echo "No script specified" && false
