language: scala

services:
  - docker

cache:
  directories:
    - "$HOME/.ivy2"

before_cache:
  - rm -Rf $HOME/.ivy2/.sbt.cache.lock
  - rm -Rf $HOME/.ivy2/.sbt.ivy.lock

env:
  global:
    - DOCKER_HOST="unix:///var/run/docker.sock"

# We define the script in the build matrix
script: echo "No script specified" && false

matrix:
  include:
    - stage: Prerequisites (level -4) blended sbt plugins
      script:
        - sh -e scripts/build-prereq.sh sbt-testlogconfig
        - sh -e scripts/build-prereq.sh sbt-jbake
        - sh -e scripts/build-prereq.sh sbt-filterresources

    - stage: Prerequisites (level -3) blended core
      script: sh -e scripts/build-prereq.sh blended

    - stage: Prerequisites (level -2) blended.itestsupport
      script: sh -e scripts/build-prereq.sh blended.itestsupport

    - stage: Prerequisites (level -1) blended.mgmt.ui
      script: sh -e scripts/build-prereq.sh blended.mgmt.ui

    - stage: Build
      name: Build and publish local
      script:
        - docker info
        - wget -P docker/blended.docker.base/files/ https://cdn.azul.com/zulu/bin/zulu8.33.0.1-jdk8.0.192-linux_x64.tar.gz
        - docker build -t atooni/blended-base docker/blended.docker.base
        - sbt publishLocal

    - stage: Test
      name: Test Node container
      script:
        - docker info
        - wget -P docker/blended.docker.base/files/ https://cdn.azul.com/zulu/bin/zulu8.33.0.1-jdk8.0.192-linux_x64.tar.gz
        - docker build -t atooni/blended-base docker/blended.docker.base
        - echo -e "-Pdocker.host=${DOCKER_HOST}\n-Pdocker.port=${DOCKER_PORT}\n" > .sbtopts
        - sbt blendedItestNode/test

    - stage: Test
      name: Test Mgmt container
      script:
        - docker info
        - wget -P docker/blended.docker.base/files/ https://cdn.azul.com/zulu/bin/zulu8.33.0.1-jdk8.0.192-linux_x64.tar.gz
        - docker build -t atooni/blended-base docker/blended.docker.base
        - echo -e "-Pdocker.host=${DOCKER_HOST}\n-Pdocker.port=${DOCKER_PORT}\n" > .sbtopts
        - sbt blendedItestMgmt/test

